/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package genricsmaxtest;

import org.junit.Test;

import com.capg.testmax.TestMaximum;

import static org.junit.Assert.*;

import org.junit.Assert;

public class TestMaximumTestCase {
	@Test
	public void givenFirst_Greater_ShouldReturnFirstInteger() {
		TestMaximum test = new TestMaximum();
		Integer result = test.maxOfThree(100, 90, 80);
		boolean finalResult=false; 
		if(result == 100) {
		finalResult = true;
		} 
		Assert.assertEquals(true, finalResult);;
	}
	@Test
	public void givenSecond_Greater_ShouldReturnSecondInteger() {
		TestMaximum test = new TestMaximum();
		Integer result = test.maxOfThree(90, 100, 80);
		boolean finalResult=false; 
		if(result == 100) {
		finalResult = true;
		} 
		Assert.assertEquals(true, finalResult);;
	}
	@Test
	public void givenThird_Greater_ShouldReturnThirdInteger() {
		TestMaximum test = new TestMaximum();
		Integer result = test.maxOfThree(90, 80, 100);
		boolean finalResult=false; 
		if(result == 100) {
		finalResult = true;
		} 
		Assert.assertEquals(true, finalResult);;
	}
}
